GET http://localhost:5153/api/products

###

GET http://localhost:5153/api/products/1

###

POST http://localhost:5153/api/products
Content-Type: application/json

{
    "id": 4,
    "name": "Product D",
    "price": 123.99
}

###

PUT http://localhost:5153/api/products/3
Content-Type: application/json

{
    "id": 3,
    "name": "Product C",
    "price": 123.99
}

###

DELETE http://localhost:5153/api/products/4